<?php

use Illuminate\Database\Seeder;

class GoodsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('goods')->delete();
        
        \DB::table('goods')->insert(array (
            0 => 
            array (
                'id' => 1,
                'uid' => 5,
                'shop_id' => 5,
                'cate_id' => 171,
                'title' => '作品1',
                'desc' => '<p>作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1</p>',
                'unit' => 0,
                'type' => 1,
                'cash' => '100.00',
                'cover' => 'attachment/sys/1a0f9310f643d740ffa22ab96af8c0fa.jpg',
                'status' => 1,
                'tool_expiration_time' => '0000-00-00 00:00:00',
                'is_recommend' => 0,
                'recommend_end' => NULL,
                'sales_num' => 0,
                'comments_num' => 0,
                'good_comment' => 0,
                'view_num' => 0,
                'is_delete' => 0,
                'recommend_text' => '',
                'seo_title' => '',
                'seo_keyword' => '',
                'seo_desc' => '',
                'created_at' => '2017-12-14 14:19:14',
                'updated_at' => '2017-12-14 14:19:56',
            ),
            1 => 
            array (
                'id' => 2,
                'uid' => 4,
                'shop_id' => 4,
                'cate_id' => 171,
                'title' => '作品2',
                'desc' => '<p>作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1</p>',
                'unit' => 0,
                'type' => 1,
                'cash' => '100.00',
                'cover' => 'attachment/sys/1a0f9310f643d740ffa22ab96af8c0fa.jpg',
                'status' => 1,
                'tool_expiration_time' => '0000-00-00 00:00:00',
                'is_recommend' => 0,
                'recommend_end' => NULL,
                'sales_num' => 0,
                'comments_num' => 0,
                'good_comment' => 0,
                'view_num' => 0,
                'is_delete' => 0,
                'recommend_text' => '',
                'seo_title' => '',
                'seo_keyword' => '',
                'seo_desc' => '',
                'created_at' => '2017-12-14 14:19:14',
                'updated_at' => '2017-12-14 14:19:56',
            ),
            2 => 
            array (
                'id' => 3,
                'uid' => 5,
                'shop_id' => 5,
                'cate_id' => 171,
                'title' => '作品3',
                'desc' => '<p>作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1</p>',
                'unit' => 0,
                'type' => 1,
                'cash' => '100.00',
                'cover' => 'attachment/sys/33cea667151b9dfd47432d3c8156dd5b.jpg',
                'status' => 1,
                'tool_expiration_time' => '0000-00-00 00:00:00',
                'is_recommend' => 0,
                'recommend_end' => NULL,
                'sales_num' => 0,
                'comments_num' => 0,
                'good_comment' => 0,
                'view_num' => 0,
                'is_delete' => 0,
                'recommend_text' => '',
                'seo_title' => '',
                'seo_keyword' => '',
                'seo_desc' => '',
                'created_at' => '2017-12-14 14:19:14',
                'updated_at' => '2017-12-14 14:19:56',
            ),
            3 => 
            array (
                'id' => 4,
                'uid' => 4,
                'shop_id' => 4,
                'cate_id' => 171,
                'title' => '作品4',
                'desc' => '<p>作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1</p>',
                'unit' => 0,
                'type' => 1,
                'cash' => '100.00',
                'cover' => 'attachment/sys/8b3a682982ad8fbad970761c83be79b2.jpg',
                'status' => 1,
                'tool_expiration_time' => '0000-00-00 00:00:00',
                'is_recommend' => 0,
                'recommend_end' => NULL,
                'sales_num' => 0,
                'comments_num' => 0,
                'good_comment' => 0,
                'view_num' => 0,
                'is_delete' => 0,
                'recommend_text' => '',
                'seo_title' => '',
                'seo_keyword' => '',
                'seo_desc' => '',
                'created_at' => '2017-12-14 14:19:14',
                'updated_at' => '2017-12-14 14:19:56',
            ),
            4 => 
            array (
                'id' => 5,
                'uid' => 6,
                'shop_id' => 6,
                'cate_id' => 171,
                'title' => '作品5',
                'desc' => '<p>作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1</p>',
                'unit' => 0,
                'type' => 1,
                'cash' => '100.00',
                'cover' => 'attachment/sys/011dacad53ff0b26871f55eba2a77c7c.jpg',
                'status' => 1,
                'tool_expiration_time' => '0000-00-00 00:00:00',
                'is_recommend' => 0,
                'recommend_end' => NULL,
                'sales_num' => 0,
                'comments_num' => 0,
                'good_comment' => 0,
                'view_num' => 0,
                'is_delete' => 0,
                'recommend_text' => '',
                'seo_title' => '',
                'seo_keyword' => '',
                'seo_desc' => '',
                'created_at' => '2017-12-14 14:19:14',
                'updated_at' => '2017-12-14 14:19:56',
            ),
            5 => 
            array (
                'id' => 6,
                'uid' => 7,
                'shop_id' => 7,
                'cate_id' => 171,
                'title' => '作品6',
                'desc' => '<p>作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1</p>',
                'unit' => 0,
                'type' => 1,
                'cash' => '100.00',
                'cover' => 'attachment/sys/1a0f9310f643d740ffa22ab96af8c0fa.jpg',
                'status' => 1,
                'tool_expiration_time' => '0000-00-00 00:00:00',
                'is_recommend' => 0,
                'recommend_end' => NULL,
                'sales_num' => 0,
                'comments_num' => 0,
                'good_comment' => 0,
                'view_num' => 0,
                'is_delete' => 0,
                'recommend_text' => '',
                'seo_title' => '',
                'seo_keyword' => '',
                'seo_desc' => '',
                'created_at' => '2017-12-14 14:19:14',
                'updated_at' => '2017-12-14 14:19:56',
            ),
            6 => 
            array (
                'id' => 7,
                'uid' => 8,
                'shop_id' => 8,
                'cate_id' => 171,
                'title' => '作品7',
                'desc' => '<p>作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1</p>',
                'unit' => 0,
                'type' => 1,
                'cash' => '100.00',
                'cover' => 'attachment/sys/1a0f9310f643d740ffa22ab96af8c0fa.jpg',
                'status' => 1,
                'tool_expiration_time' => '0000-00-00 00:00:00',
                'is_recommend' => 0,
                'recommend_end' => NULL,
                'sales_num' => 0,
                'comments_num' => 0,
                'good_comment' => 0,
                'view_num' => 0,
                'is_delete' => 0,
                'recommend_text' => '',
                'seo_title' => '',
                'seo_keyword' => '',
                'seo_desc' => '',
                'created_at' => '2017-12-14 14:19:14',
                'updated_at' => '2017-12-14 14:19:56',
            ),
            7 => 
            array (
                'id' => 8,
                'uid' => 9,
                'shop_id' => 9,
                'cate_id' => 171,
                'title' => '作品8',
                'desc' => '<p>作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1</p>',
                'unit' => 0,
                'type' => 1,
                'cash' => '100.00',
                'cover' => 'attachment/sys/1a0f9310f643d740ffa22ab96af8c0fa.jpg',
                'status' => 1,
                'tool_expiration_time' => '0000-00-00 00:00:00',
                'is_recommend' => 0,
                'recommend_end' => NULL,
                'sales_num' => 0,
                'comments_num' => 0,
                'good_comment' => 0,
                'view_num' => 0,
                'is_delete' => 0,
                'recommend_text' => '',
                'seo_title' => '',
                'seo_keyword' => '',
                'seo_desc' => '',
                'created_at' => '2017-12-14 14:19:14',
                'updated_at' => '2017-12-14 14:19:56',
            ),
            8 => 
            array (
                'id' => 9,
                'uid' => 9,
                'shop_id' => 9,
                'cate_id' => 171,
                'title' => '作品9',
                'desc' => '<p>作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1</p>',
                'unit' => 0,
                'type' => 1,
                'cash' => '100.00',
                'cover' => 'attachment/sys/1a0f9310f643d740ffa22ab96af8c0fa.jpg',
                'status' => 1,
                'tool_expiration_time' => '0000-00-00 00:00:00',
                'is_recommend' => 0,
                'recommend_end' => NULL,
                'sales_num' => 0,
                'comments_num' => 0,
                'good_comment' => 0,
                'view_num' => 0,
                'is_delete' => 0,
                'recommend_text' => '',
                'seo_title' => '',
                'seo_keyword' => '',
                'seo_desc' => '',
                'created_at' => '2017-12-14 14:19:14',
                'updated_at' => '2017-12-14 14:19:56',
            ),
            9 => 
            array (
                'id' => 10,
                'uid' => 10,
                'shop_id' => 10,
                'cate_id' => 171,
                'title' => '作品10',
                'desc' => '<p>作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1作品1</p>',
                'unit' => 0,
                'type' => 1,
                'cash' => '100.00',
                'cover' => 'attachment/sys/1a0f9310f643d740ffa22ab96af8c0fa.jpg',
                'status' => 1,
                'tool_expiration_time' => '0000-00-00 00:00:00',
                'is_recommend' => 0,
                'recommend_end' => NULL,
                'sales_num' => 0,
                'comments_num' => 0,
                'good_comment' => 0,
                'view_num' => 0,
                'is_delete' => 0,
                'recommend_text' => '',
                'seo_title' => '',
                'seo_keyword' => '',
                'seo_desc' => '',
                'created_at' => '2017-12-14 14:19:14',
                'updated_at' => '2017-12-14 14:19:56',
            ),
            10 => 
            array (
                'id' => 11,
                'uid' => 5,
                'shop_id' => 5,
                'cate_id' => 204,
                'title' => '这是一个服务1',
                'desc' => '<p>这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1</p>',
                'unit' => 0,
                'type' => 2,
                'cash' => '1000.00',
                'cover' => 'attachment/sys/aeffeb8eb61f7b4e73e3acaf2ac1a616.jpg',
                'status' => 1,
                'tool_expiration_time' => '0000-00-00 00:00:00',
                'is_recommend' => 0,
                'recommend_end' => NULL,
                'sales_num' => 0,
                'comments_num' => 0,
                'good_comment' => 0,
                'view_num' => 0,
                'is_delete' => 0,
                'recommend_text' => '',
                'seo_title' => '',
                'seo_keyword' => '',
                'seo_desc' => '',
                'created_at' => '2017-12-14 14:47:10',
                'updated_at' => '2017-12-14 14:48:45',
            ),
            11 =>
                array (
                    'id' => 12,
                    'uid' => 4,
                    'shop_id' => 4,
                    'cate_id' => 204,
                    'title' => '这是一个服务2',
                    'desc' => '<p>这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1</p>',
                    'unit' => 0,
                    'type' => 2,
                    'cash' => '1000.00',
                    'cover' => 'attachment/sys/aeffeb8eb61f7b4e73e3acaf2ac1a616.jpg',
                    'status' => 1,
                    'tool_expiration_time' => '0000-00-00 00:00:00',
                    'is_recommend' => 0,
                    'recommend_end' => NULL,
                    'sales_num' => 0,
                    'comments_num' => 0,
                    'good_comment' => 0,
                    'view_num' => 0,
                    'is_delete' => 0,
                    'recommend_text' => '',
                    'seo_title' => '',
                    'seo_keyword' => '',
                    'seo_desc' => '',
                    'created_at' => '2017-12-14 14:47:10',
                    'updated_at' => '2017-12-14 14:48:45',
                ),
            12 =>
                array (
                    'id' => 13,
                    'uid' => 6,
                    'shop_id' => 6,
                    'cate_id' => 204,
                    'title' => '这是一个服务3',
                    'desc' => '<p>这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1</p>',
                    'unit' => 0,
                    'type' => 2,
                    'cash' => '1000.00',
                    'cover' => 'attachment/sys/450c1497d50ffb58ca00e04a3f88032a.jpg',
                    'status' => 1,
                    'tool_expiration_time' => '0000-00-00 00:00:00',
                    'is_recommend' => 0,
                    'recommend_end' => NULL,
                    'sales_num' => 0,
                    'comments_num' => 0,
                    'good_comment' => 0,
                    'view_num' => 0,
                    'is_delete' => 0,
                    'recommend_text' => '',
                    'seo_title' => '',
                    'seo_keyword' => '',
                    'seo_desc' => '',
                    'created_at' => '2017-12-14 14:47:10',
                    'updated_at' => '2017-12-14 14:48:45',
                ),
            13 =>
                array (
                    'id' => 14,
                    'uid' => 7,
                    'shop_id' => 7,
                    'cate_id' => 204,
                    'title' => '这是一个服务4',
                    'desc' => '<p>这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1</p>',
                    'unit' => 0,
                    'type' => 2,
                    'cash' => '1000.00',
                    'cover' => 'attachment/sys/b3aa93ff2cdfad160fe11badfe41ffda.jpg',
                    'status' => 1,
                    'tool_expiration_time' => '0000-00-00 00:00:00',
                    'is_recommend' => 0,
                    'recommend_end' => NULL,
                    'sales_num' => 0,
                    'comments_num' => 0,
                    'good_comment' => 0,
                    'view_num' => 0,
                    'is_delete' => 0,
                    'recommend_text' => '',
                    'seo_title' => '',
                    'seo_keyword' => '',
                    'seo_desc' => '',
                    'created_at' => '2017-12-14 14:47:10',
                    'updated_at' => '2017-12-14 14:48:45',
                ),
            14 =>
                array (
                    'id' => 15,
                    'uid' => 8,
                    'shop_id' => 8,
                    'cate_id' => 204,
                    'title' => '这是一个服务5',
                    'desc' => '<p>这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1</p>',
                    'unit' => 0,
                    'type' => 2,
                    'cash' => '1000.00',
                    'cover' => 'attachment/sys/88a6256e76c533b840a015f21b2f5a29.jpg',
                    'status' => 1,
                    'tool_expiration_time' => '0000-00-00 00:00:00',
                    'is_recommend' => 0,
                    'recommend_end' => NULL,
                    'sales_num' => 0,
                    'comments_num' => 0,
                    'good_comment' => 0,
                    'view_num' => 0,
                    'is_delete' => 0,
                    'recommend_text' => '',
                    'seo_title' => '',
                    'seo_keyword' => '',
                    'seo_desc' => '',
                    'created_at' => '2017-12-14 14:47:10',
                    'updated_at' => '2017-12-14 14:48:45',
                ),
            15 =>
                array (
                    'id' => 16,
                    'uid' => 5,
                    'shop_id' => 5,
                    'cate_id' => 204,
                    'title' => '这是一个服务61',
                    'desc' => '<p>这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1</p>',
                    'unit' => 0,
                    'type' => 2,
                    'cash' => '1000.00',
                    'cover' => 'attachment/sys/aeffeb8eb61f7b4e73e3acaf2ac1a616.jpg',
                    'status' => 1,
                    'tool_expiration_time' => '0000-00-00 00:00:00',
                    'is_recommend' => 0,
                    'recommend_end' => NULL,
                    'sales_num' => 0,
                    'comments_num' => 0,
                    'good_comment' => 0,
                    'view_num' => 0,
                    'is_delete' => 0,
                    'recommend_text' => '',
                    'seo_title' => '',
                    'seo_keyword' => '',
                    'seo_desc' => '',
                    'created_at' => '2017-12-14 14:47:10',
                    'updated_at' => '2017-12-14 14:48:45',
                ),
            16 =>
                array (
                    'id' => 17,
                    'uid' => 9,
                    'shop_id' => 9,
                    'cate_id' => 204,
                    'title' => '这是一个服务9',
                    'desc' => '<p>这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1</p>',
                    'unit' => 0,
                    'type' => 2,
                    'cash' => '1000.00',
                    'cover' => 'attachment/sys/aeffeb8eb61f7b4e73e3acaf2ac1a616.jpg',
                    'status' => 1,
                    'tool_expiration_time' => '0000-00-00 00:00:00',
                    'is_recommend' => 0,
                    'recommend_end' => NULL,
                    'sales_num' => 0,
                    'comments_num' => 0,
                    'good_comment' => 0,
                    'view_num' => 0,
                    'is_delete' => 0,
                    'recommend_text' => '',
                    'seo_title' => '',
                    'seo_keyword' => '',
                    'seo_desc' => '',
                    'created_at' => '2017-12-14 14:47:10',
                    'updated_at' => '2017-12-14 14:48:45',
                ),
            17 =>
                array (
                    'id' => 18,
                    'uid' => 4,
                    'shop_id' => 4,
                    'cate_id' => 204,
                    'title' => '这是一个服务10',
                    'desc' => '<p>这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1</p>',
                    'unit' => 0,
                    'type' => 2,
                    'cash' => '1000.00',
                    'cover' => 'attachment/sys/aeffeb8eb61f7b4e73e3acaf2ac1a616.jpg',
                    'status' => 1,
                    'tool_expiration_time' => '0000-00-00 00:00:00',
                    'is_recommend' => 0,
                    'recommend_end' => NULL,
                    'sales_num' => 0,
                    'comments_num' => 0,
                    'good_comment' => 0,
                    'view_num' => 0,
                    'is_delete' => 0,
                    'recommend_text' => '',
                    'seo_title' => '',
                    'seo_keyword' => '',
                    'seo_desc' => '',
                    'created_at' => '2017-12-14 14:47:10',
                    'updated_at' => '2017-12-14 14:48:45',
                ),
            18 =>
                array (
                    'id' => 19,
                    'uid' => 11,
                    'shop_id' => 11,
                    'cate_id' => 204,
                    'title' => '这是一个服务11',
                    'desc' => '<p>这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1这是一个服务1</p>',
                    'unit' => 0,
                    'type' => 2,
                    'cash' => '1000.00',
                    'cover' => 'attachment/sys/aeffeb8eb61f7b4e73e3acaf2ac1a616.jpg',
                    'status' => 1,
                    'tool_expiration_time' => '0000-00-00 00:00:00',
                    'is_recommend' => 0,
                    'recommend_end' => NULL,
                    'sales_num' => 0,
                    'comments_num' => 0,
                    'good_comment' => 0,
                    'view_num' => 0,
                    'is_delete' => 0,
                    'recommend_text' => '',
                    'seo_title' => '',
                    'seo_keyword' => '',
                    'seo_desc' => '',
                    'created_at' => '2017-12-14 14:47:10',
                    'updated_at' => '2017-12-14 14:48:45',
                ),
        ));
        
        
    }
}
