<?php

use Illuminate\Database\Seeder;

class MenuTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu')->delete();
        
        \DB::table('menu')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => '首页',
                'route' => 'manage/',
                'pid' => 0,
                'level' => 1,
                'note' => '后台首页',
                'sort' => 0,
                'created_at' => '2016-11-01 10:55:33',
                'updated_at' => '2016-11-01 10:55:33',
            ),
            1 => 
            array (
                'id' => 36,
                'name' => '全局',
                'route' => '',
                'pid' => 0,
                'level' => 1,
                'note' => '系统配置',
                'sort' => 3,
                'created_at' => '2016-10-14 10:44:38',
                'updated_at' => '2016-10-14 10:44:38',
            ),
            2 => 
            array (
                'id' => 37,
                'name' => '系统配置',
                'route' => '',
                'pid' => 36,
                'level' => 2,
                'note' => '系统配置',
                'sort' => 1,
                'created_at' => '2016-10-13 17:52:54',
                'updated_at' => '2016-10-13 17:52:54',
            ),
            3 => 
            array (
                'id' => 38,
                'name' => '站点配置',
                'route' => 'manage/config/site',
                'pid' => 37,
                'level' => 3,
                'note' => '站点配置',
                'sort' => 1,
                'created_at' => '2016-07-16 18:40:30',
                'updated_at' => '2016-07-16 18:40:30',
            ),
            4 => 
            array (
                'id' => 39,
                'name' => '附件配置',
                'route' => 'manage/config/attachment',
                'pid' => 37,
                'level' => 3,
                'note' => '附件配置',
                'sort' => 5,
                'created_at' => '2016-10-13 18:17:17',
                'updated_at' => '2016-10-13 18:17:17',
            ),
            5 => 
            array (
                'id' => 42,
                'name' => '接口管理',
                'route' => '',
                'pid' => 36,
                'level' => 2,
                'note' => '接口管理',
                'sort' => 3,
                'created_at' => '2016-07-10 10:38:09',
                'updated_at' => '2016-07-10 10:38:09',
            ),
            6 => 
            array (
                'id' => 43,
                'name' => '支付接口',
                'route' => 'manage/payConfig',
                'pid' => 42,
                'level' => 3,
                'note' => '支付管理',
                'sort' => 3,
                'created_at' => '2016-10-14 10:28:17',
                'updated_at' => '2016-10-14 10:28:17',
            ),
            7 => 
            array (
                'id' => 44,
                'name' => 'Oauth登录',
                'route' => 'manage/thirdLogin',
                'pid' => 42,
                'level' => 3,
                'note' => '第三方登录',
                'sort' => 2,
                'created_at' => '2016-10-14 10:29:06',
                'updated_at' => '2016-10-14 10:29:06',
            ),
            8 => 
            array (
                'id' => 46,
                'name' => '协议管理',
                'route' => 'manage/agreementList',
                'pid' => 36,
                'level' => 2,
                'note' => '协议管理',
                'sort' => 5,
                'created_at' => '2016-07-14 09:12:45',
                'updated_at' => '2016-07-14 09:12:45',
            ),
            9 => 
            array (
                'id' => 48,
                'name' => '用户',
                'route' => '',
                'pid' => 0,
                'level' => 1,
                'note' => '用户管理',
                'sort' => 8,
                'created_at' => '2016-10-14 10:39:15',
                'updated_at' => '2016-10-14 10:39:15',
            ),
            10 => 
            array (
                'id' => 51,
                'name' => '认证管理',
                'route' => '',
                'pid' => 48,
                'level' => 2,
                'note' => '认证管理',
                'sort' => 3,
                'created_at' => '2016-10-14 11:48:25',
                'updated_at' => '2016-10-14 11:48:25',
            ),
            11 => 
            array (
                'id' => 52,
                'name' => '实名认证',
                'route' => 'manage/realnameAuthList',
                'pid' => 51,
                'level' => 3,
                'note' => '实名认证',
                'sort' => 1,
                'created_at' => '2016-07-14 09:12:53',
                'updated_at' => '2016-07-14 09:12:53',
            ),
            12 => 
            array (
                'id' => 53,
                'name' => '银行卡绑定',
                'route' => 'manage/bankAuthList',
                'pid' => 51,
                'level' => 3,
                'note' => '银行卡绑定',
                'sort' => 2,
                'created_at' => '2016-07-14 09:12:55',
                'updated_at' => '2016-07-14 09:12:55',
            ),
            13 => 
            array (
                'id' => 54,
                'name' => '支付宝绑定',
                'route' => 'manage/alipayAuthList',
                'pid' => 51,
                'level' => 3,
                'note' => '支付宝绑定',
                'sort' => 3,
                'created_at' => '2016-07-14 09:12:57',
                'updated_at' => '2016-07-14 09:12:57',
            ),
            14 => 
            array (
                'id' => 55,
                'name' => '用户反馈',
                'route' => '',
                'pid' => 48,
                'level' => 2,
                'note' => '用户反馈',
                'sort' => 3,
                'created_at' => '2016-07-10 10:47:59',
                'updated_at' => '2016-07-10 10:47:59',
            ),
            15 => 
            array (
                'id' => 58,
                'name' => '投诉建议',
                'route' => 'manage/feedbackList',
                'pid' => 55,
                'level' => 3,
                'note' => '投诉建议',
                'sort' => 3,
                'created_at' => '2016-07-14 09:13:05',
                'updated_at' => '2016-07-14 09:13:05',
            ),
            16 => 
            array (
                'id' => 59,
                'name' => '用户管理',
                'route' => '',
                'pid' => 48,
                'level' => 2,
                'note' => '用户管理',
                'sort' => 1,
                'created_at' => '2016-10-14 11:32:11',
                'updated_at' => '2016-10-14 11:32:11',
            ),
            17 => 
            array (
                'id' => 60,
                'name' => '系统用户',
                'route' => 'manage/managerList',
                'pid' => 59,
                'level' => 3,
                'note' => '系统用户',
                'sort' => 1,
                'created_at' => '2016-07-14 09:13:10',
                'updated_at' => '2016-07-14 09:13:10',
            ),
            18 => 
            array (
                'id' => 61,
                'name' => '普通用户',
                'route' => 'manage/userList',
                'pid' => 59,
                'level' => 3,
                'note' => '普通用户',
                'sort' => 2,
                'created_at' => '2016-07-14 09:13:13',
                'updated_at' => '2016-07-14 09:13:13',
            ),
            19 => 
            array (
                'id' => 65,
                'name' => '任务',
                'route' => '',
                'pid' => 0,
                'level' => 1,
                'note' => '任务控制台',
                'sort' => 4,
                'created_at' => '2016-10-14 10:40:08',
                'updated_at' => '2016-10-14 10:40:08',
            ),
            20 => 
            array (
                'id' => 66,
                'name' => '悬赏模式',
                'route' => '',
                'pid' => 65,
                'level' => 2,
                'note' => '任务管理',
                'sort' => 1,
                'created_at' => '2016-07-10 11:05:55',
                'updated_at' => '2016-07-10 11:05:55',
            ),
            21 => 
            array (
                'id' => 67,
                'name' => '任务列表',
                'route' => 'manage/taskList',
                'pid' => 66,
                'level' => 3,
                'note' => '任务列表',
                'sort' => 1,
                'created_at' => '2016-07-14 09:13:28',
                'updated_at' => '2016-07-14 09:13:28',
            ),
            22 => 
            array (
                'id' => 68,
                'name' => '行业管理',
                'route' => 'manage/industry',
                'pid' => 36,
                'level' => 2,
                'note' => '行业分类',
                'sort' => 2,
                'created_at' => '2016-10-14 10:26:34',
                'updated_at' => '2016-10-14 10:26:34',
            ),
            23 => 
            array (
                'id' => 80,
                'name' => '工具',
                'route' => '',
                'pid' => 0,
                'level' => 1,
                'note' => '站长工具',
                'sort' => 9,
                'created_at' => '2016-10-14 10:41:45',
                'updated_at' => '2016-10-14 10:41:45',
            ),
            24 => 
            array (
                'id' => 84,
                'name' => '资讯',
                'route' => '',
                'pid' => 0,
                'level' => 1,
                'note' => '资讯管理',
                'sort' => 6,
                'created_at' => '2016-10-14 10:40:55',
                'updated_at' => '2016-10-14 10:40:55',
            ),
            25 => 
            array (
                'id' => 85,
                'name' => '页脚配置',
                'route' => '',
                'pid' => 84,
                'level' => 2,
                'note' => '页脚配置',
                'sort' => 3,
                'created_at' => '2016-10-14 13:55:11',
                'updated_at' => '2016-10-14 13:55:11',
            ),
            26 => 
            array (
                'id' => 86,
                'name' => '文章信息',
                'route' => '',
                'pid' => 84,
                'level' => 2,
                'note' => '文章模块',
                'sort' => 2,
                'created_at' => '2016-10-14 13:54:17',
                'updated_at' => '2016-10-14 13:54:17',
            ),
            27 => 
            array (
                'id' => 87,
                'name' => '成功案例',
                'route' => '',
                'pid' => 84,
                'level' => 2,
                'note' => '成功案例',
                'sort' => 1,
                'created_at' => '2016-10-14 13:44:02',
                'updated_at' => '2016-10-14 13:44:02',
            ),
            28 => 
            array (
                'id' => 88,
                'name' => '页脚管理',
                'route' => 'manage/articleFooter/3',
                'pid' => 85,
                'level' => 3,
                'note' => '页脚管理',
                'sort' => 1,
                'created_at' => '2016-08-04 16:50:09',
                'updated_at' => '2016-08-04 16:50:09',
            ),
            29 => 
            array (
                'id' => 89,
                'name' => '页脚分类',
                'route' => 'manage/categoryFooterList/3',
                'pid' => 85,
                'level' => 3,
                'note' => '页脚分类',
                'sort' => 2,
                'created_at' => '2016-08-04 17:48:07',
                'updated_at' => '2016-08-04 17:48:07',
            ),
            30 => 
            array (
                'id' => 90,
                'name' => '文章管理',
                'route' => 'manage/article/1',
                'pid' => 86,
                'level' => 3,
                'note' => '文章管理',
                'sort' => 1,
                'created_at' => '2016-07-14 09:14:28',
                'updated_at' => '2016-07-14 09:14:28',
            ),
            31 => 
            array (
                'id' => 91,
                'name' => '文章分类',
                'route' => 'manage/categoryList/1',
                'pid' => 86,
                'level' => 3,
                'note' => '文章分类',
                'sort' => 2,
                'created_at' => '2016-08-04 15:46:02',
                'updated_at' => '2016-08-04 15:46:02',
            ),
            32 => 
            array (
                'id' => 92,
                'name' => '案例管理',
                'route' => 'manage/successCaseList',
                'pid' => 87,
                'level' => 3,
                'note' => '案例列表',
                'sort' => 1,
                'created_at' => '2016-10-14 13:45:59',
                'updated_at' => '2016-10-14 13:45:59',
            ),
            33 => 
            array (
                'id' => 94,
                'name' => '财务',
                'route' => '',
                'pid' => 0,
                'level' => 1,
                'note' => '财务管理',
                'sort' => 7,
                'created_at' => '2016-10-14 10:41:16',
                'updated_at' => '2016-10-14 10:41:16',
            ),
            34 => 
            array (
                'id' => 95,
                'name' => '财务报表',
                'route' => '',
                'pid' => 94,
                'level' => 2,
                'note' => '财务概况',
                'sort' => 1,
                'created_at' => '2016-10-14 13:27:29',
                'updated_at' => '2016-10-14 13:27:29',
            ),
            35 => 
            array (
                'id' => 96,
                'name' => '网站收支',
                'route' => 'manage/financeStatement',
                'pid' => 95,
                'level' => 3,
                'note' => '网站收支',
                'sort' => 1,
                'created_at' => '2016-07-14 09:15:10',
                'updated_at' => '2016-07-14 09:15:10',
            ),
            36 => 
            array (
                'id' => 97,
                'name' => '充值记录',
                'route' => 'manage/financeRecharge',
                'pid' => 95,
                'level' => 3,
                'note' => '充值记录',
                'sort' => 2,
                'created_at' => '2016-07-14 09:15:13',
                'updated_at' => '2016-07-14 09:15:13',
            ),
            37 => 
            array (
                'id' => 98,
                'name' => '提现记录',
                'route' => 'manage/financeWithdraw',
                'pid' => 95,
                'level' => 3,
                'note' => '提现记录',
                'sort' => 3,
                'created_at' => '2016-07-14 09:15:15',
                'updated_at' => '2016-07-14 09:15:15',
            ),
            38 => 
            array (
                'id' => 99,
                'name' => '利润统计',
                'route' => 'manage/financeProfit',
                'pid' => 95,
                'level' => 3,
                'note' => '利润统计',
                'sort' => 4,
                'created_at' => '2016-07-14 09:15:17',
                'updated_at' => '2016-07-14 09:15:17',
            ),
            39 => 
            array (
                'id' => 104,
                'name' => '消息',
                'route' => '',
                'pid' => 0,
                'level' => 1,
                'note' => '短信模板 系统消息',
                'sort' => 10,
                'created_at' => '2016-10-14 10:42:22',
                'updated_at' => '2016-10-14 10:42:22',
            ),
            40 => 
            array (
                'id' => 105,
                'name' => '消息模板',
                'route' => 'manage/messageList',
                'pid' => 104,
                'level' => 2,
                'note' => '短信模板列表',
                'sort' => 1,
                'created_at' => '2016-10-14 14:35:32',
                'updated_at' => '2016-10-14 14:35:32',
            ),
            41 => 
            array (
                'id' => 108,
                'name' => '店铺',
                'route' => '',
                'pid' => 0,
                'level' => 1,
                'note' => '店铺管理',
                'sort' => 4,
                'created_at' => '2016-10-14 15:30:23',
                'updated_at' => '2016-10-14 15:30:23',
            ),
            42 => 
            array (
                'id' => 110,
                'name' => '流程配置',
                'route' => 'manage/employConfig',
                'pid' => 109,
                'level' => 3,
                'note' => '',
                'sort' => 1,
                'created_at' => '2016-10-14 11:46:59',
                'updated_at' => '2016-10-14 11:46:59',
            ),
            43 => 
            array (
                'id' => 112,
                'name' => '订单管理',
                'route' => 'manage/employList',
                'pid' => 109,
                'level' => 3,
                'note' => '雇佣列表',
                'sort' => 0,
                'created_at' => '2016-10-14 11:46:30',
                'updated_at' => '2016-10-14 11:46:30',
            ),
            44 => 
            array (
                'id' => 113,
                'name' => '企业认证',
                'route' => '/manage/enterpriseAuthList',
                'pid' => 51,
                'level' => 3,
                'note' => '企业认证列表',
                'sort' => 4,
                'created_at' => '2016-10-14 11:48:50',
                'updated_at' => '2016-10-14 11:48:50',
            ),
            45 => 
            array (
                'id' => 119,
                'name' => '作品管理',
                'route' => '',
                'pid' => 108,
                'level' => 2,
                'note' => '',
                'sort' => 3,
                'created_at' => '2016-10-14 11:50:17',
                'updated_at' => '2016-10-14 11:50:17',
            ),
            46 => 
            array (
                'id' => 120,
                'name' => '作品管理',
                'route' => '/manage/goodsList ',
                'pid' => 119,
                'level' => 3,
                'note' => '',
                'sort' => 1,
                'created_at' => '2016-10-14 11:51:17',
                'updated_at' => '2016-10-14 11:51:17',
            ),
            47 => 
            array (
                'id' => 121,
                'name' => '订单管理',
                'route' => '/manage/shopOrderList',
                'pid' => 119,
                'level' => 3,
                'note' => '',
                'sort' => 0,
                'created_at' => '2016-10-14 15:28:25',
                'updated_at' => '2016-10-14 11:51:17',
            ),
            48 => 
            array (
                'id' => 122,
                'name' => '流程配置',
                'route' => '/manage/goodsConfig ',
                'pid' => 119,
                'level' => 3,
                'note' => '',
                'sort' => 2,
                'created_at' => '2016-10-14 11:52:02',
                'updated_at' => '2016-10-14 11:52:02',
            ),
            49 => 
            array (
                'id' => 123,
                'name' => '威客服务',
                'route' => '',
                'pid' => 108,
                'level' => 2,
                'note' => '威客服务',
                'sort' => 2,
                'created_at' => '2016-10-14 11:49:13',
                'updated_at' => '2016-10-14 11:49:13',
            ),
            50 => 
            array (
                'id' => 125,
                'name' => '订单管理',
                'route' => '/manage/serviceOrderList',
                'pid' => 123,
                'level' => 3,
                'note' => '订单管理',
                'sort' => 1,
                'created_at' => '2016-10-14 15:28:26',
                'updated_at' => '2016-10-14 11:51:17',
            ),
            51 => 
            array (
                'id' => 126,
                'name' => '服务管理',
                'route' => '/manage/goodsServiceList',
                'pid' => 123,
                'level' => 3,
                'note' => '服务管理',
                'sort' => 2,
                'created_at' => '2016-09-22 16:45:08',
                'updated_at' => '2016-09-22 16:45:08',
            ),
            52 => 
            array (
                'id' => 127,
                'name' => '流程配置',
                'route' => '/manage/serviceConfig',
                'pid' => 123,
                'level' => 3,
                'note' => '流程配置',
                'sort' => 3,
                'created_at' => '2016-10-14 15:28:27',
                'updated_at' => '2016-10-14 11:51:17',
            ),
            53 => 
            array (
                'id' => 132,
                'name' => '自定义导航',
                'route' => 'manage/navList ',
                'pid' => 37,
                'level' => 3,
                'note' => '自定义导航',
                'sort' => 2,
                'created_at' => '2016-10-14 15:28:29',
                'updated_at' => '2016-10-14 11:51:17',
            ),
            54 => 
            array (
                'id' => 133,
                'name' => '菜单管理',
                'route' => 'manage/menuList/1/1 ',
                'pid' => 37,
                'level' => 3,
                'note' => '菜单管理',
                'sort' => 3,
                'created_at' => '2016-10-14 10:38:02',
                'updated_at' => '2016-10-14 10:38:02',
            ),
            55 => 
            array (
                'id' => 134,
                'name' => '模板管理',
                'route' => '/manage/skin',
                'pid' => 37,
                'level' => 3,
                'note' => '',
                'sort' => 6,
                'created_at' => '2016-10-14 15:28:29',
                'updated_at' => '2016-10-14 11:51:17',
            ),
            56 => 
            array (
                'id' => 135,
                'name' => '推荐管理',
                'route' => '',
                'pid' => 36,
                'level' => 2,
                'note' => '',
                'sort' => 4,
                'created_at' => '2016-10-14 15:28:30',
                'updated_at' => '2016-10-14 11:51:17',
            ),
            57 => 
            array (
                'id' => 136,
                'name' => '广告管理',
                'route' => '/advertisement/adTarget',
                'pid' => 135,
                'level' => 3,
                'note' => '',
                'sort' => 1,
                'created_at' => '2016-10-14 10:50:33',
                'updated_at' => '2016-10-14 10:50:33',
            ),
            58 => 
            array (
                'id' => 137,
                'name' => '推荐位管理',
                'route' => '/advertisement/recommendList',
                'pid' => 135,
                'level' => 3,
                'note' => '',
                'sort' => 2,
                'created_at' => '2016-10-14 10:55:10',
                'updated_at' => '2016-10-14 10:55:10',
            ),
            59 => 
            array (
                'id' => 138,
                'name' => '友情链接',
                'route' => '/manage/link',
                'pid' => 135,
                'level' => 3,
                'note' => '',
                'sort' => 3,
                'created_at' => '2016-10-14 11:30:12',
                'updated_at' => '2016-10-14 11:30:12',
            ),
            60 => 
            array (
                'id' => 139,
                'name' => '权限管理',
                'route' => '',
                'pid' => 48,
                'level' => 2,
                'note' => '',
                'sort' => 2,
                'created_at' => '2016-10-14 11:33:49',
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 140,
                'name' => '角色管理',
                'route' => '/manage/rolesList',
                'pid' => 139,
                'level' => 3,
                'note' => '',
                'sort' => 1,
                'created_at' => '2016-10-14 11:34:31',
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 141,
                'name' => '店铺管理',
                'route' => '',
                'pid' => 108,
                'level' => 2,
                'note' => '',
                'sort' => 0,
                'created_at' => '2016-10-14 15:29:53',
                'updated_at' => '2016-10-14 15:29:53',
            ),
            63 => 
            array (
                'id' => 142,
                'name' => '店铺信息',
                'route' => '/manage/shopList',
                'pid' => 141,
                'level' => 3,
                'note' => '',
                'sort' => 0,
                'created_at' => '2016-10-14 11:40:35',
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 143,
                'name' => '店铺配置',
                'route' => '/manage/shopConfig',
                'pid' => 141,
                'level' => 3,
                'note' => '店铺配置',
                'sort' => 1,
                'created_at' => '2016-10-14 11:42:23',
                'updated_at' => '2016-10-14 11:42:23',
            ),
            65 => 
            array (
                'id' => 144,
                'name' => '权限设置',
                'route' => '/manage/permissionsList',
                'pid' => 139,
                'level' => 3,
                'note' => '',
                'sort' => 2,
                'created_at' => '2016-10-14 11:45:24',
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 145,
                'name' => '交易反馈',
                'route' => '',
                'pid' => 108,
                'level' => 2,
                'note' => '',
                'sort' => 4,
                'created_at' => '2016-10-14 11:53:14',
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 146,
                'name' => '交易维权',
                'route' => '/manage/ShopRightsList',
                'pid' => 145,
                'level' => 3,
                'note' => '',
                'sort' => 0,
                'created_at' => '2016-10-14 11:54:06',
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 149,
                'name' => '互评记录',
                'route' => '/manage/getCommentList',
                'pid' => 65,
                'level' => 2,
                'note' => '',
                'sort' => 3,
                'created_at' => '2016-10-14 13:06:20',
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 150,
                'name' => '举报维权',
                'route' => '',
                'pid' => 65,
                'level' => 2,
                'note' => '',
                'sort' => 4,
                'created_at' => '2016-10-14 13:09:40',
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 151,
                'name' => '交易举报',
                'route' => '/manage/reportList',
                'pid' => 150,
                'level' => 3,
                'note' => '',
                'sort' => 1,
                'created_at' => '2016-10-14 13:10:23',
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 152,
                'name' => '交易维权',
                'route' => '/manage/rightsList',
                'pid' => 150,
                'level' => 3,
                'note' => '',
                'sort' => 2,
                'created_at' => '2016-10-14 13:15:22',
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 153,
                'name' => '充值提现',
                'route' => '',
                'pid' => 94,
                'level' => 2,
                'note' => '',
                'sort' => 2,
                'created_at' => '2016-10-14 13:28:14',
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 154,
                'name' => '财务流水',
                'route' => '',
                'pid' => 94,
                'level' => 2,
                'note' => '',
                'sort' => 3,
                'created_at' => '2016-10-14 13:28:32',
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 155,
                'name' => '充值记录',
                'route' => '/manage/rechargeList',
                'pid' => 153,
                'level' => 3,
                'note' => '',
                'sort' => 1,
                'created_at' => '2016-10-14 13:29:27',
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 156,
                'name' => '提现记录',
                'route' => '/manage/cashoutList',
                'pid' => 153,
                'level' => 3,
                'note' => '',
                'sort' => 2,
                'created_at' => '2016-10-14 13:34:16',
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 157,
                'name' => '网站流水',
                'route' => '/manage/financeList',
                'pid' => 154,
                'level' => 3,
                'note' => '',
                'sort' => 1,
                'created_at' => '2016-10-14 13:39:00',
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 159,
                'name' => '用户流水',
                'route' => '/manage/userFinance',
                'pid' => 154,
                'level' => 3,
                'note' => '',
                'sort' => 2,
                'created_at' => '2016-10-14 13:52:47',
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 160,
                'name' => '站长工具',
                'route' => '',
                'pid' => 80,
                'level' => 2,
                'note' => '',
                'sort' => 0,
                'created_at' => '2016-10-14 14:23:22',
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 161,
                'name' => '系统日志',
                'route' => 'manage/systemLogList',
                'pid' => 160,
                'level' => 3,
                'note' => '系统日志',
                'sort' => 1,
                'created_at' => '2016-10-14 14:27:36',
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 162,
                'name' => '附件管理',
                'route' => 'manage/attachmentList',
                'pid' => 160,
                'level' => 3,
                'note' => '附件管理',
                'sort' => 2,
                'created_at' => '2016-10-14 14:30:02',
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 163,
                'name' => '增值工具',
                'route' => '',
                'pid' => 80,
                'level' => 2,
                'note' => '',
                'sort' => 1,
                'created_at' => '2016-10-17 11:17:23',
                'updated_at' => '2016-10-17 11:17:23',
            ),
            82 => 
            array (
                'id' => 164,
                'name' => '工具列表',
                'route' => 'manage/serviceList',
                'pid' => 163,
                'level' => 3,
                'note' => '工具列表',
                'sort' => 1,
                'created_at' => '2016-10-17 11:17:02',
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 165,
                'name' => '雇佣管理',
                'route' => '',
                'pid' => 108,
                'level' => 2,
                'note' => '',
                'sort' => 1,
                'created_at' => '2016-10-17 11:31:10',
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 166,
                'name' => '订单管理',
                'route' => '/manage/employList',
                'pid' => 165,
                'level' => 3,
                'note' => '订单管理',
                'sort' => 1,
                'created_at' => '2016-10-17 11:32:09',
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 167,
                'name' => '流程配置',
                'route' => '/manage/employConfig',
                'pid' => 165,
                'level' => 3,
                'note' => '流程配置',
                'sort' => 2,
                'created_at' => '2016-10-17 11:33:10',
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 171,
                'name' => '应用',
                'route' => '',
                'pid' => 0,
                'level' => 1,
                'note' => '应用管理',
                'sort' => 11,
                'created_at' => '2016-10-18 10:16:28',
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 172,
                'name' => '问答中心',
                'route' => '',
                'pid' => 171,
                'level' => 2,
                'note' => '问答中心',
                'sort' => 1,
                'created_at' => '2016-10-18 10:29:50',
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => 173,
                'name' => '问答列表',
                'route' => 'manage/questionList',
                'pid' => 172,
                'level' => 3,
                'note' => '问答列表',
                'sort' => 1,
                'created_at' => '2016-10-18 10:30:33',
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => 174,
                'name' => '问答配置',
                'route' => 'manage/questionConfig',
                'pid' => 172,
                'level' => 3,
                'note' => '问答配置',
                'sort' => 2,
                'created_at' => '2016-10-18 10:31:25',
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'id' => 175,
                'name' => '地区管理',
                'route' => '/manage/area',
                'pid' => 37,
                'level' => 3,
                'note' => '',
                'sort' => 4,
                'created_at' => '2016-10-19 10:13:34',
                'updated_at' => NULL,
            ),
            /**91 => 
            array (
                'id' => 176,
                'name' => '推广营销',
                'route' => '',
                'pid' => 171,
                'level' => 2,
                'note' => '推广营销',
                'sort' => 2,
                'created_at' => '2016-10-20 13:12:54',
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => 177,
                'name' => '推广配置',
                'route' => 'manage/promoteConfig',
                'pid' => 176,
                'level' => 3,
                'note' => '推广配置',
                'sort' => 1,
                'created_at' => '2016-10-21 14:00:17',
                'updated_at' => '2016-10-21 14:00:17',
            ),
            93 => 
            array (
                'id' => 178,
                'name' => '推广关系',
                'route' => 'manage/promoteRelation',
                'pid' => 176,
                'level' => 3,
                'note' => '推广关系',
                'sort' => 2,
                'created_at' => '2016-10-21 15:05:41',
                'updated_at' => '2016-10-21 15:05:41',
            ),
            94 => 
            array (
                'id' => 179,
                'name' => '推广财务',
                'route' => 'manage/promoteFinance',
                'pid' => 176,
                'level' => 3,
                'note' => '推广财务',
                'sort' => 3,
                'created_at' => '2016-10-21 15:33:28',
                'updated_at' => '2016-10-21 15:33:28',
            ),
            95 => 
            array (
                'id' => 184,
                'name' => 'vip管理',
                'route' => '',
                'pid' => 108,
                'level' => 2,
                'note' => 'vip管理',
                'sort' => 0,
                'created_at' => '2016-11-01 10:55:47',
                'updated_at' => '2016-11-01 10:55:47',
            ),
            96 => 
            array (
                'id' => 185,
                'name' => '首页配置',
                'route' => '/manage/vipConfig',
                'pid' => 184,
                'level' => 3,
                'note' => 'vip首页配置',
                'sort' => 0,
                'created_at' => '2016-11-01 11:09:50',
                'updated_at' => '2016-11-01 11:09:50',
            ),
            97 => 
            array (
                'id' => 186,
                'name' => '套餐管理',
                'route' => '/manage/vipPackageList',
                'pid' => 184,
                'level' => 3,
                'note' => '套餐管理',
                'sort' => 1,
                'created_at' => '2016-11-01 11:03:01',
                'updated_at' => '2016-11-01 11:03:01',
            ),
            98 => 
            array (
                'id' => 187,
                'name' => '特权管理',
                'route' => '/manage/vipInfoList',
                'pid' => 184,
                'level' => 3,
                'note' => '特权列表',
                'sort' => 2,
                'created_at' => '2016-11-01 11:09:26',
                'updated_at' => '2016-11-01 11:09:26',
            ),
            99 => 
            array (
                'id' => 188,
                'name' => 'vip店铺',
                'route' => '/manage/vipShopList',
                'pid' => 184,
                'level' => 3,
                'note' => 'vip店铺',
                'sort' => 3,
                'created_at' => '2016-11-01 11:05:28',
                'updated_at' => '2016-11-01 11:05:28',
            ),
            100 => 
            array (
                'id' => 189,
                'name' => '访谈管理',
                'route' => '/manage/vipDetailsList',
                'pid' => 184,
                'level' => 3,
                'note' => '访谈列表',
                'sort' => 4,
                'created_at' => '2016-11-01 11:09:09',
                'updated_at' => '2016-11-01 11:09:09',
            ),*/
            101 => 
            array (
                'id' => 190,
                'name' => '招标模式',
                'route' => '',
                'pid' => 65,
                'level' => 2,
                'note' => '招标管理',
                'sort' => 2,
                'created_at' => '2017-09-11 14:49:52',
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'id' => 191,
                'name' => '任务列表',
                'route' => '/manage/bidList',
                'pid' => 190,
                'level' => 3,
                'note' => '任务列表',
                'sort' => 1,
                'created_at' => '2017-09-11 14:51:02',
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'id' => 192,
                'name' => '任务配置',
                'route' => 'manage/bidConfig/1',
                'pid' => 190,
                'level' => 3,
                'note' => '任务配置',
                'sort' => 2,
                'created_at' => '2017-09-11 14:52:41',
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'id' => 193,
                'name' => '任务配置',
                'route' => 'manage/taskConfig/1',
                'pid' => 66,
                'level' => 3,
                'note' => '任务配置',
                'sort' => 2,
                'created_at' => '2017-09-11 14:53:36',
                'updated_at' => NULL,
            ),
            /*105 => 
            array (
                'id' => 194,
                'name' => '接入交付台',
                'route' => '/manage/keeLoad',
                'pid' => 80,
                'level' => 2,
                'note' => '',
                'sort' => 3,
                'created_at' => '2017-12-07 11:47:41',
                'updated_at' => NULL,
            ),*/
        ));
        
        
    }
}
