<?php

use Illuminate\Database\Seeder;

class PrivilegesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('privileges')->delete();
        
        \DB::table('privileges')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'test',
                'desc' => 'dhhh',
                'code' => NULL,
                'list' => 0,
                'type' => 0,
                'status' => 1,
                'is_recommend' => 0,
                'ico' => '',
                'created_at' => '2016-11-02 17:41:39',
                'updated_at' => '2016-11-17 13:33:18',
                'deleted_at' => '2016-11-17 13:33:18',
            ),
            1 => 
            array (
                'id' => 3,
                'title' => 'VIP头像皇冠',
                'desc' => 'VIP头像皇冠',
                'code' => NULL,
                'list' => 0,
                'type' => 0,
                'status' => 0,
                'is_recommend' => 1,
                'ico' => '',
                'created_at' => '2016-11-17 14:21:24',
                'updated_at' => '2016-11-17 14:23:00',
                'deleted_at' => '2016-11-17 14:23:00',
            ),
            2 => 
            array (
                'id' => 4,
                'title' => 'fghffg',
                'desc' => 'hjhjhyjh',
                'code' => NULL,
                'list' => 0,
                'type' => 0,
                'status' => 0,
                'is_recommend' => 0,
                'ico' => '',
                'created_at' => '2016-11-08 13:08:16',
                'updated_at' => '2016-11-17 13:33:16',
                'deleted_at' => '2016-11-17 13:33:16',
            ),
            3 => 
            array (
                'id' => 5,
                'title' => '1',
                'desc' => 'kjkjukj',
                'code' => NULL,
                'list' => 0,
                'type' => 0,
                'status' => 1,
                'is_recommend' => 0,
                'ico' => '',
                'created_at' => '2016-11-17 13:33:01',
                'updated_at' => '2016-11-17 13:33:09',
                'deleted_at' => '2016-11-17 13:33:09',
            ),
            4 => 
            array (
                'id' => 6,
                'title' => 'kjkjkj',
                'desc' => 'kjkjkj',
                'code' => NULL,
                'list' => 0,
                'type' => 0,
                'status' => 1,
                'is_recommend' => 0,
                'ico' => '',
                'created_at' => NULL,
                'updated_at' => '2016-11-17 13:33:21',
                'deleted_at' => '2016-11-17 13:33:21',
            ),
            5 => 
            array (
                'id' => 7,
                'title' => 'kjkjkj',
                'desc' => 'fdfdf',
                'code' => NULL,
                'list' => 0,
                'type' => 0,
                'status' => 0,
                'is_recommend' => 0,
                'ico' => '',
                'created_at' => NULL,
                'updated_at' => '2016-11-17 13:33:23',
                'deleted_at' => '2016-11-17 13:33:23',
            ),
            6 => 
            array (
                'id' => 8,
                'title' => 'hghghg',
                'desc' => 'hjhj',
                'code' => NULL,
                'list' => 0,
                'type' => 0,
                'status' => 0,
                'is_recommend' => 0,
                'ico' => '',
                'created_at' => NULL,
                'updated_at' => '2016-11-17 13:33:31',
                'deleted_at' => '2016-11-17 13:33:31',
            ),
            7 => 
            array (
                'id' => 9,
                'title' => 'ghggh',
                'desc' => 'j,kl,k',
                'code' => NULL,
                'list' => 0,
                'type' => 0,
                'status' => 0,
                'is_recommend' => 0,
                'ico' => '',
                'created_at' => NULL,
                'updated_at' => '2016-11-17 13:33:33',
                'deleted_at' => '2016-11-17 13:33:33',
            ),
            8 => 
            array (
                'id' => 10,
                'title' => 'dsdsds',
                'desc' => 'hjhjh',
                'code' => NULL,
                'list' => 0,
                'type' => 0,
                'status' => 1,
                'is_recommend' => 0,
                'ico' => '',
                'created_at' => NULL,
                'updated_at' => '2016-11-17 13:42:59',
                'deleted_at' => '2016-11-17 13:42:59',
            ),
            9 => 
            array (
                'id' => 11,
                'title' => 'bbgbgbg',
                'desc' => 'bgbgb',
                'code' => NULL,
                'list' => 2,
                'type' => 0,
                'status' => 0,
                'is_recommend' => 1,
                'ico' => 'attachment\\sys\\8f7a292b3603fded497c37c3424b9fca.gif',
                'created_at' => '2016-11-09 14:11:58',
                'updated_at' => '2016-11-17 13:43:13',
                'deleted_at' => '2016-11-17 13:43:13',
            ),
            10 => 
            array (
                'id' => 12,
                'title' => 'hgfjgfjd',
                'desc' => 'fdfdfdf',
                'code' => NULL,
                'list' => 3,
                'type' => 0,
                'status' => 1,
                'is_recommend' => 1,
                'ico' => 'attachment\\sys\\ffc707daf8664a096f42dcdb90cf952c.gif',
                'created_at' => '2016-11-09 15:26:47',
                'updated_at' => '2016-11-17 13:43:17',
                'deleted_at' => '2016-11-17 13:43:17',
            ),
            11 => 
            array (
                'id' => 13,
                'title' => 'ggfdgfd',
                'desc' => 'gdfgfdg',
                'code' => NULL,
                'list' => 3,
                'type' => 0,
                'status' => 0,
                'is_recommend' => 1,
                'ico' => 'attachment\\sys\\3bc273c0cc335f690f2dcc076e7e12a0.gif',
                'created_at' => '2016-11-09 17:20:43',
                'updated_at' => '2016-11-17 13:43:15',
                'deleted_at' => '2016-11-17 13:43:15',
            ),
            12 => 
            array (
                'id' => 14,
                'title' => 'nbvcbcb',
                'desc' => 'wewewewe',
                'code' => NULL,
                'list' => 0,
                'type' => 0,
                'status' => 0,
                'is_recommend' => 0,
                'ico' => 'attachment\\sys\\9393f77adb9839f8bfe84c5cca6b55d6.gif',
                'created_at' => '2016-11-11 11:33:21',
                'updated_at' => '2016-11-17 13:33:13',
                'deleted_at' => '2016-11-17 13:33:13',
            ),
            13 => 
            array (
                'id' => 15,
                'title' => '店铺装修',
                'desc' => '店铺装修',
                'code' => 'SHOP_DECORATION',
                'list' => 0,
                'type' => 1,
                'status' => 0,
                'is_recommend' => 1,
                'ico' => 'attachment/sys/3698d47556f53f44d4ba502fa9799c2d.jpg',
                'created_at' => '2016-11-18 18:17:37',
                'updated_at' => '2016-11-18 18:17:37',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 16,
                'title' => 'hghghg',
                'desc' => 'hghghgh',
                'code' => NULL,
                'list' => 1,
                'type' => 0,
                'status' => 0,
                'is_recommend' => 1,
                'ico' => 'attachment\\sys\\3f72599cacbc1107fd739a30ffc5e642.gif',
                'created_at' => '2016-11-11 13:51:56',
                'updated_at' => '2016-11-17 13:43:01',
                'deleted_at' => '2016-11-17 13:43:01',
            ),
            15 => 
            array (
                'id' => 17,
                'title' => 'bdnfdfndfd',
                'desc' => 'fdfndfdfdmfd',
                'code' => NULL,
                'list' => 2,
                'type' => 0,
                'status' => 0,
                'is_recommend' => 1,
                'ico' => 'attachment\\sys\\9f13f69697ad0783d0bbb2e4580d6fc2.gif',
                'created_at' => '2016-11-11 16:37:19',
                'updated_at' => '2016-11-17 13:43:11',
                'deleted_at' => '2016-11-17 13:43:11',
            ),
            16 => 
            array (
                'id' => 18,
                'title' => 'vip身份标识',
                'desc' => 'vip装逼身份标识',
                'code' => NULL,
                'list' => 1,
                'type' => 0,
                'status' => 0,
                'is_recommend' => 1,
                'ico' => 'attachment/sys/53e649a46144d1ff41ca6f48c62f1604.jpg',
                'created_at' => '2016-11-18 18:18:48',
                'updated_at' => '2016-11-18 18:18:48',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 19,
                'title' => 'VIP店铺营销',
                'desc' => 'VIP装逼店铺营销',
                'code' => NULL,
                'list' => 2,
                'type' => 0,
                'status' => 0,
                'is_recommend' => 1,
                'ico' => 'attachment/sys/1339caa1a3001fc126677750a4342431.png',
                'created_at' => '2016-11-18 18:18:56',
                'updated_at' => '2016-11-18 18:18:56',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 20,
                'title' => '黄金广告位',
                'desc' => '黄金广告位',
                'code' => NULL,
                'list' => 3,
                'type' => 0,
                'status' => 0,
                'is_recommend' => 1,
                'ico' => 'attachment/sys/590b1051821a17a31e0803b136a85577.jpg',
                'created_at' => '2016-11-18 18:19:06',
                'updated_at' => '2016-11-18 18:19:06',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 21,
                'title' => '金牌客服',
                'desc' => '金牌客服',
                'code' => NULL,
                'list' => 4,
                'type' => 0,
                'status' => 0,
                'is_recommend' => 1,
                'ico' => 'attachment/sys/c9ba1e2da5e3c1e0f1abd481d72e6899.png',
                'created_at' => '2016-11-18 18:19:21',
                'updated_at' => '2016-11-18 18:19:21',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 22,
                'title' => '强势品牌推荐',
                'desc' => '强势品牌推荐',
                'code' => NULL,
                'list' => 5,
                'type' => 0,
                'status' => 0,
                'is_recommend' => 1,
                'ico' => 'attachment/sys/bb0079eddd6b783ccc0295ac0e332d8f.jpg',
                'created_at' => '2016-11-18 18:19:29',
                'updated_at' => '2016-11-18 18:19:29',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 23,
                'title' => '测试特权',
                'desc' => '测试特权',
                'code' => NULL,
                'list' => 6,
                'type' => 0,
                'status' => 0,
                'is_recommend' => 0,
                'ico' => 'attachment/sys/074f865ee697e7a16708a12793bbdfa3.png',
                'created_at' => '2016-11-30 15:29:12',
                'updated_at' => '2016-12-12 14:32:28',
                'deleted_at' => '2016-12-12 14:32:28',
            ),
            22 => 
            array (
                'id' => 24,
                'title' => '测试特权',
                'desc' => '测试特权',
                'code' => NULL,
                'list' => 6,
                'type' => 0,
                'status' => 0,
                'is_recommend' => 0,
                'ico' => 'attachment/sys/b0f3b9906062c58aca0bb401c3615538.jpg',
                'created_at' => '2016-12-12 14:33:07',
                'updated_at' => '2016-12-12 14:33:24',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}
