<?php

use Illuminate\Database\Seeder;

class TaskTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('task')->delete();
        
        \DB::table('task')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => '渔具品牌取名',
            'desc' => '<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 20px;">渔具品牌取名</span><p style="margin-bottom: 5px; padding: 0px; border: 0px; line-height: 30px; color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px;"></p><p style="margin-bottom: 5px; padding: 0px; border: 0px; line-height: 30px; color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px;">欢迎参加“渔具品牌取名”任务，具体要求如下：<br><br>1、要求作品风格明显，令人过目不忘，郎郎上口；<br><br>2、主题突出，寓意深刻，适合渔具、户外产品；<br><br>3、最好有相应中、英文名，日本名字也行；<br><br>4、所起名字必须符合国家工商注册标准，本名称是用来注册商标的，递交前请查实能否注册，如果不能注册，请勿递交；<br><br>5. 要求原创，并附上创意说明 。<br></p>',
                'type_id' => 1,
                'cate_id' => 239,
                'phone' => '15902765682',
                'region_limit' => 0,
                'status' => 1,
                'bounty' => '10000.00',
                'bounty_status' => 0,
                'verified_at' => NULL,
                'begin_at' => '2016-08-03 00:00:00',
                'end_at' => NULL,
                'delivery_deadline' => '2018-08-10 00:00:00',
                'selected_work_at' => NULL,
                'publicity_at' => NULL,
                'checked_at' => NULL,
                'comment_at' => NULL,
                'show_cash' => '10000.00',
                'real_cash' => '0.00',
                'deposit_cash' => '0.00',
                'province' => 17,
                'city' => 37,
                'area' => 0,
                'view_count' => NULL,
                'delivery_count' => NULL,
                'uid' => 1,
                'username' => NULL,
                'worker_num' => 1,
                'top_status' => 1,
                'service' => NULL,
                'task_success_draw_ratio' => 0,
                'task_fail_draw_ratio' => 0,
                'created_at' => '2016-08-03 15:51:11',
                'updated_at' => '2016-08-03 15:51:11',
            ),
            1 => 
            array (
                'id' => 2,
                'title' => '渔具品牌取名',
            'desc' => '<span style="color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 30px;">1、要求作品风格明显，令人过目不忘，郎郎上口；</span><br style="color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 30px;"><br style="color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 30px;"><span style="color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 30px;">2、主题突出，寓意深刻，适合渔具、户外产品；</span><br style="color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 30px;"><br style="color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 30px;"><span style="color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 30px;">3、最好有相应中、英文名，日本名字也行；</span><br style="color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 30px;"><br style="color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 30px;"><span style="color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 30px;">4、所起名字必须符合国家工商注册标准，本名称是用来注册商标的，递交前请查实能否注册，如果不能注册，请勿递交；</span><br style="color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 30px;"><br style="color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 30px;"><span style="color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 30px;">5. 要求原创，并附上创意说明 。</span><br style="color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 30px;">',
                'type_id' => 1,
                'cate_id' => 171,
                'phone' => '15902765682',
                'region_limit' => 0,
                'status' => 3,
                'bounty' => '5000.00',
                'bounty_status' => 1,
                'verified_at' => NULL,
                'begin_at' => '2016-08-04 00:00:00',
                'end_at' => NULL,
                'delivery_deadline' => '2018-08-24 00:00:00',
                'selected_work_at' => NULL,
                'publicity_at' => NULL,
                'checked_at' => NULL,
                'comment_at' => NULL,
                'show_cash' => '5000.00',
                'real_cash' => '0.00',
                'deposit_cash' => '0.00',
                'province' => 1,
                'city' => 37,
                'area' => 0,
                'view_count' => NULL,
                'delivery_count' => NULL,
                'uid' => 1,
                'username' => NULL,
                'worker_num' => 1,
                'top_status' => 1,
                'service' => NULL,
                'task_success_draw_ratio' => 0,
                'task_fail_draw_ratio' => 0,
                'created_at' => '2016-08-03 16:09:24',
                'updated_at' => '2016-08-03 16:22:10',
            ),
            2 => 
            array (
                'id' => 3,
                'title' => '厦门小吃餐厅营销方案',
            'desc' => '<p style="margin-bottom: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 12px; line-height: 24px;"><span style="font-weight: 700;">客家人”厦门经营特色小吃的餐厅，LOGO设计及简单应用</span></p><p style="margin-bottom: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 12px; line-height: 24px;"><span style="font-weight: 700;">经营介绍：</span>&nbsp;“客家人”是一家以经营特色小吃为主的快餐餐厅特色餐品“客家人”是用独特的传统工艺制作而成，口感独特，明显区别其它面种，传承百年，获奖无数。</p><p style="margin-bottom: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 12px; line-height: 24px;"><span style="font-weight: 700;">VI应用内容：</span>设计LOGO、店面招牌设计(竖排，横排)、菜牌、名片、餐巾纸、筷子纸筒、牙签包装 、员工胸牌、服装设计。</p><p style="margin-bottom: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 12px; line-height: 24px;"><span style="font-weight: 700;">设计要求：</span></p><ul class="ml_20" style="margin-bottom: 0px; margin-left: 20px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 12px; line-height: 24px;"><li style="margin: 0px; padding: 0px; list-style: none;">1、大气、简洁、明快;</li><li style="margin: 0px; padding: 0px; list-style: none;">2、有视觉冲击力，醒目易识别，突出餐饮品牌元素;</li><li style="margin: 0px; padding: 0px; list-style: none;">3、能体现特色，LOGO已有，但如限制了设计师的创意，可重新设计。</li><li style="margin: 0px; padding: 0px; list-style: none;">4、附上创意说明。</li></ul><p style="margin-bottom: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 12px; line-height: 24px;"><span style="font-weight: 700;">知识产权说明：</span></p><ul class="ml_20" style="margin-bottom: 0px; margin-left: 20px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 12px; line-height: 24px;"><li style="margin: 0px; padding: 0px; list-style: none;">1、所设计的作品为原创，为第一次发布，未侵犯他人的著作权，如有侵犯他人著作权，由设计者承担所有法律责任;</li><li style="margin: 0px; padding: 0px; list-style: none;">2、中标的设计作品，我方支付设计制作费，即拥有该作品的知识产权，包括著作权,使用权和发布权等,有权对设计作品进行修改,组合和应用;设计者不得再向其他任何地方使用该设计作品;</li></ul>',
                'type_id' => 1,
                'cate_id' => 174,
                'phone' => '15874587458',
                'region_limit' => 0,
                'status' => 3,
                'bounty' => '3000.00',
                'bounty_status' => 1,
                'verified_at' => NULL,
                'begin_at' => '2016-08-03 00:00:00',
                'end_at' => NULL,
                'delivery_deadline' => '2018-08-04 00:00:00',
                'selected_work_at' => NULL,
                'publicity_at' => NULL,
                'checked_at' => NULL,
                'comment_at' => NULL,
                'show_cash' => '3000.00',
                'real_cash' => '0.00',
                'deposit_cash' => '0.00',
                'province' => 1,
                'city' => 37,
                'area' => 0,
                'view_count' => NULL,
                'delivery_count' => NULL,
                'uid' => 2,
                'username' => NULL,
                'worker_num' => 1,
                'top_status' => 1,
                'service' => NULL,
                'task_success_draw_ratio' => 0,
                'task_fail_draw_ratio' => 0,
                'created_at' => '2016-08-03 16:13:55',
                'updated_at' => '2016-08-03 16:14:01',
            ),
            3 => 
            array (
                'id' => 4,
                'title' => '厦门小吃餐厅营销方案',
            'desc' => '<p style="margin-bottom: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 12px; line-height: 24px;"><span style="font-weight: 700;">客家人”厦门经营特色小吃的餐厅，LOGO设计及简单应用</span></p><p style="margin-bottom: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 12px; line-height: 24px;"><span style="font-weight: 700;">经营介绍：</span>&nbsp;“客家人”是一家以经营特色小吃为主的快餐餐厅特色餐品“客家人”是用独特的传统工艺制作而成，口感独特，明显区别其它面种，传承百年，获奖无数。</p><p style="margin-bottom: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 12px; line-height: 24px;"><span style="font-weight: 700;">VI应用内容：</span>设计LOGO、店面招牌设计(竖排，横排)、菜牌、名片、餐巾纸、筷子纸筒、牙签包装 、员工胸牌、服装设计。</p><p style="margin-bottom: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 12px; line-height: 24px;"><span style="font-weight: 700;">设计要求：</span></p><ul class="ml_20" style="margin-bottom: 0px; margin-left: 20px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 12px; line-height: 24px;"><li style="margin: 0px; padding: 0px; list-style: none;">1、大气、简洁、明快;</li><li style="margin: 0px; padding: 0px; list-style: none;">2、有视觉冲击力，醒目易识别，突出餐饮品牌元素;</li><li style="margin: 0px; padding: 0px; list-style: none;">3、能体现特色，LOGO已有，但如限制了设计师的创意，可重新设计。</li><li style="margin: 0px; padding: 0px; list-style: none;">4、附上创意说明。</li></ul><p style="margin-bottom: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 12px; line-height: 24px;"><span style="font-weight: 700;">知识产权说明：</span></p><ul class="ml_20" style="margin-bottom: 0px; margin-left: 20px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 12px; line-height: 24px;"><li style="margin: 0px; padding: 0px; list-style: none;">1、所设计的作品为原创，为第一次发布，未侵犯他人的著作权，如有侵犯他人著作权，由设计者承担所有法律责任;</li><li style="margin: 0px; padding: 0px; list-style: none;">2、中标的设计作品，我方支付设计制作费，即拥有该作品的知识产权，包括著作权,使用权和发布权等,有权对设计作品进行修改,组合和应用;设计者不得再向其他任何地方使用该设计作品;</li></ul>',
                'type_id' => 1,
                'cate_id' => 175,
                'phone' => '15874587458',
                'region_limit' => 0,
                'status' => 0,
                'bounty' => '1000.00',
                'bounty_status' => 0,
                'verified_at' => NULL,
                'begin_at' => '2016-08-03 00:00:00',
                'end_at' => NULL,
                'delivery_deadline' => '2018-08-04 00:00:00',
                'selected_work_at' => NULL,
                'publicity_at' => NULL,
                'checked_at' => NULL,
                'comment_at' => NULL,
                'show_cash' => '1000.00',
                'real_cash' => '0.00',
                'deposit_cash' => '0.00',
                'province' => 1,
                'city' => 37,
                'area' => 0,
                'view_count' => NULL,
                'delivery_count' => NULL,
                'uid' => 2,
                'username' => NULL,
                'worker_num' => 1,
                'top_status' => 0,
                'service' => NULL,
                'task_success_draw_ratio' => 0,
                'task_fail_draw_ratio' => 0,
                'created_at' => '2016-08-03 16:14:42',
                'updated_at' => '2016-08-03 16:14:42',
            ),
            4 => 
            array (
                'id' => 5,
                'title' => '沐风环保LOGO设计',
            'desc' => '<span style="color: rgb(102, 102, 102); font-family: \'Microsoft YaHei\', sans-serif; line-height: 24px;">我司主营范围是空气净化系统方案供应。武汉沐风环保工程有限公司是一家多年来专业从事各式厨房排油烟及新风系统工程的系统设计、制造、安装及售后服务于一体的科技型环保企业。可承接各式大型商业体整体排烟、新风、天然气事故强排等系统设计、系统施工及售后作业；承接各类大中型餐饮酒店、快餐连锁、美食广场以及企事业机关、大中专院校食堂厨房的排烟系统工程新建或改造工程。</span><br style="color: rgb(102, 102, 102); font-family: \'Microsoft YaHei\', sans-serif; line-height: 24px;"><span style="color: rgb(102, 102, 102); font-family: \'Microsoft YaHei\', sans-serif; line-height: 24px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;其LOGO要求色彩不要太多，简洁...</span>',
                'type_id' => 1,
                'cate_id' => 179,
                'phone' => '15902765682',
                'region_limit' => 0,
                'status' => 1,
                'bounty' => '2000.00',
                'bounty_status' => 0,
                'verified_at' => NULL,
                'begin_at' => '2016-08-04 00:00:00',
                'end_at' => NULL,
                'delivery_deadline' => '2018-08-15 00:00:00',
                'selected_work_at' => NULL,
                'publicity_at' => NULL,
                'checked_at' => NULL,
                'comment_at' => NULL,
                'show_cash' => '2000.00',
                'real_cash' => '0.00',
                'deposit_cash' => '0.00',
                'province' => 1,
                'city' => 37,
                'area' => 0,
                'view_count' => NULL,
                'delivery_count' => NULL,
                'uid' => 5,
                'username' => NULL,
                'worker_num' => 5,
                'top_status' => 1,
                'service' => NULL,
                'task_success_draw_ratio' => 0,
                'task_fail_draw_ratio' => 0,
                'created_at' => '2016-08-03 16:17:13',
                'updated_at' => '2016-08-03 16:17:13',
            ),
            5 => 
            array (
                'id' => 6,
                'title' => '论坛帖子推广，在一些知名的金融理财，财经网站上面发帖推广',
            'desc' => '<div class="task_info_ti<x>tle yahei" style="font-family: \'Microsoft YaHei\', sans-serif; color: rgb(102, 102, 102); font-weight: bold;"><div class="task_info_ti<x>tle yahei" style="font-family: \'Microsoft YaHei\', sans-serif;"><span style="font-weight: normal; line-height: 24px;">1、是否有软文：无</span><br style="font-weight: normal; line-height: 24px;"><span style="font-weight: normal; line-height: 24px;">2、发帖数量和价格：每贴2元</span><br style="font-weight: normal; line-height: 24px;"><span style="font-weight: normal; line-height: 24px;">3、发帖内容要求：帖子标题内容看附件</span><br style="font-weight: normal; line-height: 24px;"><span style="font-weight: normal; line-height: 24px;">4、发帖类型要求：财经，金融，理财，金融网站和一些，猫扑，西祠，天涯，等论坛上面发帖子，每个论坛最多两个。</span><br style="font-weight: normal; line-height: 24px;"><span style="font-weight: normal; line-height: 24px;">5、发帖时间要求：两天时间完成发布7月12-7月15日</span><br style="font-weight: normal; line-height: 24px;"><span style="font-weight: normal; line-height: 24px;">6、其他要求：需保证纯手工发布，不注册也能够看到，并且必须被百度，谷歌，收录,完成后发链接或者截图验证</span><br></div><div class="task_info_content yahei hidden" style="font-family: \'Microsoft YaHei\', sans-serif; word-wrap: break-word; word-break: break-all; line-height: 2; margin-top: 5px; min-height: 150px; display: block; font-weight: normal;"><div>1、是否有软文：无<br>2、发帖数量和价格：每贴2元<br>3、发帖内容要求：帖子标题内容看附件<br>4、发帖类型要求：财经，金融，理财，金融网站和一些，猫扑，西祠，天涯，等论坛上面发帖子，每个论坛最多两个。<br>5、发帖时间要求：两天时间完成发布7月12-7月15日<br></div></div></div><div class="task_info_content yahei hidden" style="font-family: \'Microsoft YaHei\', sans-serif; color: rgb(102, 102, 102); word-wrap: break-word; word-break: break-all; line-height: 2; margin-top: 5px; min-height: 150px; display: block;"><div>1、是否有软文：无<br>2、发帖数量和价格：每贴2元<br>3、发帖内容要求：帖子标题内容看附件<br>4、发帖类型要求：财经，金融，理财，金融网站和一些，猫扑，西祠，天涯，等论坛上面发帖子，每个论坛最多两个。<br>5、发帖时间要求：两天时间完成发布7月12-7月15日<br></div></div>',
                'type_id' => 1,
                'cate_id' => 178,
                'phone' => '15902765682',
                'region_limit' => 0,
                'status' => 3,
                'bounty' => '5000.00',
                'bounty_status' => 1,
                'verified_at' => NULL,
                'begin_at' => '2016-08-03 00:00:00',
                'end_at' => NULL,
                'delivery_deadline' => '2018-08-20 00:00:00',
                'selected_work_at' => NULL,
                'publicity_at' => NULL,
                'checked_at' => NULL,
                'comment_at' => NULL,
                'show_cash' => '5000.00',
                'real_cash' => '0.00',
                'deposit_cash' => '0.00',
                'province' => 1,
                'city' => 37,
                'area' => 0,
                'view_count' => NULL,
                'delivery_count' => NULL,
                'uid' => 1,
                'username' => NULL,
                'worker_num' => 20,
                'top_status' => 1,
                'service' => NULL,
                'task_success_draw_ratio' => 0,
                'task_fail_draw_ratio' => 0,
                'created_at' => '2016-08-03 16:28:58',
                'updated_at' => '2016-08-03 16:29:52',
            ),
            6 => 
            array (
                'id' => 7,
                'title' => '融资咨询网站ui设计和静态页面制作开发',
            'desc' => '<span style="margin: 0px; padding: 0px; border: 0px; font-size: 14px; color: rgb(102, 102, 102); font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; line-height: 25.2px;">1、按附件要求完成12个页面的设计和开发，最后给出html页面即可，后台交互不需要理会；</span><br style="color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 20px;"><span style="margin: 0px; padding: 0px; border: 0px; font-size: 14px; color: rgb(102, 102, 102); font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; line-height: 25.2px;">2、部分页面按要求完成相关js的效果的编写；</span><br style="color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 20px;"><span style="margin: 0px; padding: 0px; border: 0px; font-size: 14px; color: rgb(102, 102, 102); font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; line-height: 25.2px;">3、主色调红色、配色调黄色；</span><span style="color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 20px;">&nbsp;任务附件&nbsp;</span><span class="ceb2" style="margin: 0px; padding: 0px; border: 0px; color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 20px;">(1)</span><span style="color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 20px;">&nbsp;</span><img class="access_pic" src="http://www.epwk.com/tpl/default/theme/simple/img/task/access_file.gif" style="margin: 0px; padding: 0px; border-style: initial; color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 20px;"><span style="color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px; line-height: 20px;">&nbsp;需求说明和页面原型.zip (1.16M)&nbsp;下</span>',
                'type_id' => 1,
                'cate_id' => 237,
                'phone' => '15902765682',
                'region_limit' => 0,
                'status' => 3,
                'bounty' => '5000.00',
                'bounty_status' => 1,
                'verified_at' => NULL,
                'begin_at' => '2016-08-03 00:00:00',
                'end_at' => NULL,
                'delivery_deadline' => '2018-08-16 00:00:00',
                'selected_work_at' => NULL,
                'publicity_at' => NULL,
                'checked_at' => NULL,
                'comment_at' => NULL,
                'show_cash' => '5000.00',
                'real_cash' => '0.00',
                'deposit_cash' => '0.00',
                'province' => 1,
                'city' => 37,
                'area' => 0,
                'view_count' => NULL,
                'delivery_count' => NULL,
                'uid' => 1,
                'username' => NULL,
                'worker_num' => 10,
                'top_status' => 1,
                'service' => NULL,
                'task_success_draw_ratio' => 0,
                'task_fail_draw_ratio' => 0,
                'created_at' => '2016-08-03 16:33:20',
                'updated_at' => '2016-08-03 16:33:25',
            ),
            7 => 
            array (
                'id' => 8,
                'title' => '简益LOGO设计',
            'desc' => '<span style="color: rgb(102, 102, 102); font-family: \'Microsoft YaHei\', sans-serif; line-height: 24px;">我们是广东百科律师事务所下面的一个团队,我们团队的LOGO&nbsp;是&nbsp;"简益"(大道至简,人同我益)。&nbsp;</span><br style="color: rgb(102, 102, 102); font-family: \'Microsoft YaHei\', sans-serif; line-height: 24px;"><span style="color: rgb(102, 102, 102); font-family: \'Microsoft YaHei\', sans-serif; line-height: 24px;">现在要求设计名片及&nbsp;"简益"二字的LOGO。</span><br style="color: rgb(102, 102, 102); font-family: \'Microsoft YaHei\', sans-serif; line-height: 24px;"><span style="color: rgb(102, 102, 102); font-family: \'Microsoft YaHei\', sans-serif; line-height: 24px;">名片要中文和英文两面，如附件所示我现在的名片。但是我们的名片不需要原来律所的蓝红LOGO了，用“简益”的LOGO。</span><br style="color: rgb(102, 102, 102); font-family: \'Microsoft YaHei\', sans-serif; line-height: 24px;"><span style="color: rgb(102, 102, 102); font-family: \'Microsoft YaHei\', sans-serif; line-height: 24px;">名片要求&nbsp;高大上，正面是个人信息，背面是视觉效果的设计。背面要求附上我们的理念，大道至简，人同我益</span>',
                'type_id' => 1,
                'cate_id' => 186,
                'phone' => '15902765682',
                'region_limit' => 0,
                'status' => 3,
                'bounty' => '3000.00',
                'bounty_status' => 1,
                'verified_at' => NULL,
                'begin_at' => '2016-08-03 00:00:00',
                'end_at' => NULL,
                'delivery_deadline' => '2018-08-20 00:00:00',
                'selected_work_at' => NULL,
                'publicity_at' => NULL,
                'checked_at' => NULL,
                'comment_at' => NULL,
                'show_cash' => '3000.00',
                'real_cash' => '0.00',
                'deposit_cash' => '0.00',
                'province' => 1,
                'city' => 37,
                'area' => 0,
                'view_count' => NULL,
                'delivery_count' => NULL,
                'uid' => 1,
                'username' => NULL,
                'worker_num' => 1,
                'top_status' => 1,
                'service' => NULL,
                'task_success_draw_ratio' => 0,
                'task_fail_draw_ratio' => 0,
                'created_at' => '2016-08-03 16:37:46',
                'updated_at' => '2016-08-03 16:37:52',
            ),
            8 => 
            array (
                'id' => 9,
                'title' => '厦门小吃餐厅营销方案',
            'desc' => '<p style="margin-bottom: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 12px; line-height: 24px;"><span style="font-weight: 700;">客家人”厦门经营特色小吃的餐厅，LOGO设计及简单应用</span></p><p style="margin-bottom: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 12px; line-height: 24px;"><span style="font-weight: 700;">经营介绍：</span>&nbsp;“客家人”是一家以经营特色小吃为主的快餐餐厅特色餐品“客家人”是用独特的传统工艺制作而成，口感独特，明显区别其它面种，传承百年，获奖无数。</p><p style="margin-bottom: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 12px; line-height: 24px;"><span style="font-weight: 700;">VI应用内容：</span>设计LOGO、店面招牌设计(竖排，横排)、菜牌、名片、餐巾纸、筷子纸筒、牙签包装 、员工胸牌、服装设计。</p><p style="margin-bottom: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 12px; line-height: 24px;"><span style="font-weight: 700;">设计要求：</span></p><ul class="ml_20" style="margin-bottom: 0px; margin-left: 20px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 12px; line-height: 24px;"><li style="margin: 0px; padding: 0px; list-style: none;">1、大气、简洁、明快;</li><li style="margin: 0px; padding: 0px; list-style: none;">2、有视觉冲击力，醒目易识别，突出餐饮品牌元素;</li><li style="margin: 0px; padding: 0px; list-style: none;">3、能体现特色，LOGO已有，但如限制了设计师的创意，可重新设计。</li><li style="margin: 0px; padding: 0px; list-style: none;">4、附上创意说明。</li></ul><p style="margin-bottom: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 12px; line-height: 24px;"><span style="font-weight: 700;">知识产权说明：</span></p><ul class="ml_20" style="margin-bottom: 0px; margin-left: 20px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 12px; line-height: 24px;"><li style="margin: 0px; padding: 0px; list-style: none;">1、所设计的作品为原创，为第一次发布，未侵犯他人的著作权，如有侵犯他人著作权，由设计者承担所有法律责任;</li><li style="margin: 0px; padding: 0px; list-style: none;">2、中标的设计作品，我方支付设计制作费，即拥有该作品的知识产权，包括著作权,使用权和发布权等,有权对设计作品进行修改,组合和应用;设计者不得再向其他任何地方使用该设计作品;</li></ul>',
                'type_id' => 1,
                'cate_id' => 177,
                'phone' => '15858965896',
                'region_limit' => 0,
                'status' => 3,
                'bounty' => '1111.00',
                'bounty_status' => 1,
                'verified_at' => NULL,
                'begin_at' => '2016-08-03 00:00:00',
                'end_at' => NULL,
                'delivery_deadline' => '2018-08-04 00:00:00',
                'selected_work_at' => NULL,
                'publicity_at' => NULL,
                'checked_at' => NULL,
                'comment_at' => NULL,
                'show_cash' => '1111.00',
                'real_cash' => '0.00',
                'deposit_cash' => '0.00',
                'province' => 1,
                'city' => 37,
                'area' => 0,
                'view_count' => NULL,
                'delivery_count' => NULL,
                'uid' => 2,
                'username' => NULL,
                'worker_num' => 1,
                'top_status' => 0,
                'service' => NULL,
                'task_success_draw_ratio' => 0,
                'task_fail_draw_ratio' => 0,
                'created_at' => '2016-08-03 16:40:34',
                'updated_at' => '2016-08-03 16:40:40',
            ),
            9 => 
            array (
                'id' => 10,
                'title' => '矿泉水市场策划',
            'desc' => '<span style="color: rgb(102, 102, 102); font-family: 微软雅黑, sans-serif; line-height: normal;">品牌整体市场策划方案。 只做省内市场</span>',
                'type_id' => 1,
                'cate_id' => 181,
                'phone' => '15902765682',
                'region_limit' => 0,
                'status' => 3,
                'bounty' => '8500.00',
                'bounty_status' => 1,
                'verified_at' => NULL,
                'begin_at' => '2016-08-03 00:00:00',
                'end_at' => NULL,
                'delivery_deadline' => '2018-08-20 00:00:00',
                'selected_work_at' => NULL,
                'publicity_at' => NULL,
                'checked_at' => NULL,
                'comment_at' => NULL,
                'show_cash' => '8500.00',
                'real_cash' => '0.00',
                'deposit_cash' => '0.00',
                'province' => 1,
                'city' => 37,
                'area' => 0,
                'view_count' => NULL,
                'delivery_count' => NULL,
                'uid' => 1,
                'username' => NULL,
                'worker_num' => 1,
                'top_status' => 1,
                'service' => NULL,
                'task_success_draw_ratio' => 0,
                'task_fail_draw_ratio' => 0,
                'created_at' => '2016-08-03 16:42:00',
                'updated_at' => '2016-08-03 16:42:05',
            ),
            10 => 
            array (
                'id' => 11,
                'title' => '1756棋牌游戏代练',
            'desc' => '<p style="margin-bottom: 5px; padding: 0px; border: 0px; line-height: 30px; color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px;">游戏中不能使用外挂等作弊软件，以及发送一些诋毁游戏的消息，否则会被封号。如果账号被封，你将拿不到工资哦。交稿后账号将被收回。我提供账号、密码，不提供游戏币，游戏币自理，不能修改游戏密码。若无心代练，切勿浪费大家的时间和精神.。&nbsp;</p><p style="margin-bottom: 5px; padding: 0px; border: 0px; line-height: 30px; color: rgb(51, 51, 51); font-family: 微软雅黑, \'Hiragino Sans GB\'; font-size: 14px;">&nbsp;&nbsp;&nbsp;&nbsp; 要求 。在宝藏扑克累计赢取70亿金币。不提供游戏币， 在规定时间内完不成没工资。自发任务起20天内完成。请看好要求</p>',
                'type_id' => 1,
                'cate_id' => 229,
                'phone' => '15902765682',
                'region_limit' => 0,
                'status' => 4,
                'bounty' => '5000.00',
                'bounty_status' => 1,
                'verified_at' => NULL,
                'begin_at' => '2016-08-03 00:00:00',
                'end_at' => NULL,
                'delivery_deadline' => '2018-08-20 00:00:00',
                'selected_work_at' => NULL,
                'publicity_at' => NULL,
                'checked_at' => NULL,
                'comment_at' => NULL,
                'show_cash' => '5000.00',
                'real_cash' => '0.00',
                'deposit_cash' => '0.00',
                'province' => 1,
                'city' => 37,
                'area' => 0,
                'view_count' => NULL,
                'delivery_count' => NULL,
                'uid' => 1,
                'username' => NULL,
                'worker_num' => 1,
                'top_status' => 1,
                'service' => NULL,
                'task_success_draw_ratio' => 0,
                'task_fail_draw_ratio' => 0,
                'created_at' => '2016-08-03 16:45:40',
                'updated_at' => '2016-08-03 16:58:24',
            ),
            11 => 
            array (
                'id' => 12,
                'title' => '蓝牙pos机线下线上推广 ',
                'desc' => '线下可以地推可选DM传单，摆摊面对面等销售，线上微信等推广<br>主要面对广东范围（可以全国）<br>目标人群:有信用卡人士<br>1.指导客户注册并且激活使用蓝牙手机POS机.<br>2.完成一笔一定金额的刷卡才算激活.<br>3做好服务跟踪.帮助客户解决遇到的相关问题<br>任务报酬说明（包括基础报酬、绩效奖励规则、验收扣薪规则）：<br>基本薪资：每注册激活一个用户并成功完成一笔一定金额的刷卡的.可获得35元<br>提成：每激活满10个用户，再获得100元奖励。<br>其他条件可再议<br><br>来源：http://task.zbj.com/7971560/<br>',
                'type_id' => 1,
                'cate_id' => 181,
                'phone' => '13275689653',
                'region_limit' => 0,
                'status' => 3,
                'bounty' => '3000.00',
                'bounty_status' => 1,
                'verified_at' => NULL,
                'begin_at' => '2016-08-03 00:00:00',
                'end_at' => NULL,
                'delivery_deadline' => '2018-08-16 00:00:00',
                'selected_work_at' => NULL,
                'publicity_at' => NULL,
                'checked_at' => NULL,
                'comment_at' => NULL,
                'show_cash' => '3000.00',
                'real_cash' => '0.00',
                'deposit_cash' => '0.00',
                'province' => 1,
                'city' => 37,
                'area' => 0,
                'view_count' => NULL,
                'delivery_count' => NULL,
                'uid' => 3,
                'username' => NULL,
                'worker_num' => 10,
                'top_status' => 1,
                'service' => NULL,
                'task_success_draw_ratio' => 0,
                'task_fail_draw_ratio' => 0,
                'created_at' => '2016-08-03 16:56:45',
                'updated_at' => '2016-08-03 16:56:51',
            ),
            12 => 
            array (
                'id' => 13,
                'title' => '澳洲跑腿工LOGO设计',
                'desc' => '公司名称：澳洲跑腿工（ozpaotui）<br>公司均主营澳洲的母婴跟保健品系列，涉及澳洲部分的化妆品以及零食等。&nbsp;&nbsp;<br>要求：<br>公司logo:要求是卡通形象，要有袋鼠图案，并突出ozpaotui，要活泼积极向上。&nbsp;&nbsp;<br>需要有创意，适合网络营销好记形象化设计，给人新奇<br>&nbsp;logo要整体圆润，看上去醒目。<br><br><br>来源：http://task.zbj.com/7971499/###<br>',
                'type_id' => 1,
                'cate_id' => 185,
                'phone' => '13275689653',
                'region_limit' => 0,
                'status' => 3,
                'bounty' => '400.00',
                'bounty_status' => 1,
                'verified_at' => NULL,
                'begin_at' => '2016-08-03 00:00:00',
                'end_at' => NULL,
                'delivery_deadline' => '2018-08-09 00:00:00',
                'selected_work_at' => NULL,
                'publicity_at' => NULL,
                'checked_at' => NULL,
                'comment_at' => NULL,
                'show_cash' => '400.00',
                'real_cash' => '0.00',
                'deposit_cash' => '0.00',
                'province' => 1,
                'city' => 37,
                'area' => 0,
                'view_count' => NULL,
                'delivery_count' => NULL,
                'uid' => 3,
                'username' => NULL,
                'worker_num' => 10,
                'top_status' => 0,
                'service' => NULL,
                'task_success_draw_ratio' => 0,
                'task_fail_draw_ratio' => 0,
                'created_at' => '2016-08-03 16:58:53',
                'updated_at' => '2016-08-03 16:58:59',
            ),
            13 => 
            array (
                'id' => 14,
                'title' => '思密达咖啡LOGO设计',
                'desc' => '需要制作logo的酒店名称：思密达咖啡<br>酒店定位：韩国时尚咖啡品牌。<br>品牌诠释：源自韩国的咖啡文化，激发灵感的醇香记忆，是都市人旅居及生活中不可或缺的时尚元素。<br>项
目概述：&nbsp;韩潮集团是中国韩尚风格酒店创始者。集团以韩国时尚文化为背景，致力成为中韩时尚&nbsp;文化的桥梁，从满足消费者时尚需求及情感诉求出发，为消费者
获得更多的消费体验和情感投射打造品牌多元化及未来美好生活体验圈。集团旗下拥有思密达酒店、橙色酒店、韩舍酒店、罗曼丽舍酒店、漫约酒店、艾未来酒店、
韩漫SPA酒店、千家住酒店等酒店品牌及思密达咖啡食品连锁品牌。&nbsp;韩潮集团以“让每一座城市都充满爱”为使命，以“成为客户最喜爱的酒店品牌”为
目&nbsp;标，以“爱就在你身边”为服务理念，以韩尚风格形成差异化品牌区隔，开辟蓝海，抢占消费者心智，全心全意满足消费者对美好生活的向往，成为中国市场最
具人文情怀及情感共鸣的连锁品牌集团。',
                'type_id' => 1,
                'cate_id' => 187,
                'phone' => '13275689653',
                'region_limit' => 0,
                'status' => 1,
                'bounty' => '1050.00',
                'bounty_status' => 0,
                'verified_at' => NULL,
                'begin_at' => '2016-08-03 00:00:00',
                'end_at' => NULL,
                'delivery_deadline' => '2018-08-15 00:00:00',
                'selected_work_at' => NULL,
                'publicity_at' => NULL,
                'checked_at' => NULL,
                'comment_at' => NULL,
                'show_cash' => '1050.00',
                'real_cash' => '0.00',
                'deposit_cash' => '0.00',
                'province' => 1,
                'city' => 37,
                'area' => 0,
                'view_count' => NULL,
                'delivery_count' => NULL,
                'uid' => 3,
                'username' => NULL,
                'worker_num' => 10,
                'top_status' => 0,
                'service' => NULL,
                'task_success_draw_ratio' => 0,
                'task_fail_draw_ratio' => 0,
                'created_at' => '2016-08-03 17:01:16',
                'updated_at' => '2016-08-03 17:01:16',
            ),
            14 => 
            array (
                'id' => 15,
                'title' => '需要制作logo的酒店名称：思密达咖啡',
                'desc' => '需要制作logo的酒店名称：思密达咖啡<br>酒店定位：韩国时尚咖啡品牌。<br>品牌诠释：源自韩国的咖啡文化，激发灵感的醇香记忆，是都市人旅居及生活中不可或缺的时尚元素。<br>项
目概述：&nbsp;韩潮集团是中国韩尚风格酒店创始者。集团以韩国时尚文化为背景，致力成为中韩时尚&nbsp;文化的桥梁，从满足消费者时尚需求及情感诉求出发，为消费者
获得更多的消费体验和情感投射打造品牌多元化及未来美好生活体验圈。集团旗下拥有思密达酒店、橙色酒店、韩舍酒店、罗曼丽舍酒店、漫约酒店、艾未来酒店、
韩漫SPA酒店、千家住酒店等酒店品牌及思密达咖啡食品连锁品牌。&nbsp;韩潮集团以“让每一座城市都充满爱”为使命，以“成为客户最喜爱的酒店品牌”为
目&nbsp;标，以“爱就在你身边”为服务理念，以韩尚风格形成差异化品牌区隔，开辟蓝海，抢占消费者心智，全心全意满足消费者对美好生活的向往，成为中国市场最
具人文情怀及情感共鸣的连锁品牌集团。',
                'type_id' => 1,
                'cate_id' => 190,
                'phone' => '13275689653',
                'region_limit' => 0,
                'status' => 3,
                'bounty' => '1050.00',
                'bounty_status' => 1,
                'verified_at' => NULL,
                'begin_at' => '2016-08-03 00:00:00',
                'end_at' => NULL,
                'delivery_deadline' => '2018-08-15 00:00:00',
                'selected_work_at' => NULL,
                'publicity_at' => NULL,
                'checked_at' => NULL,
                'comment_at' => NULL,
                'show_cash' => '1050.00',
                'real_cash' => '0.00',
                'deposit_cash' => '0.00',
                'province' => 1,
                'city' => 37,
                'area' => 0,
                'view_count' => NULL,
                'delivery_count' => NULL,
                'uid' => 3,
                'username' => NULL,
                'worker_num' => 10,
                'top_status' => 0,
                'service' => NULL,
                'task_success_draw_ratio' => 0,
                'task_fail_draw_ratio' => 0,
                'created_at' => '2016-08-03 17:34:01',
                'updated_at' => '2016-08-03 17:34:07',
            ),
        ));
        
        
    }
}
